# Generated by Django 4.2.3 on 2023-07-29 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('picture1', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/', verbose_name='Картинка1')),
                ('picture2', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/', verbose_name='Картинка2')),
                ('picture3', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/', verbose_name='Картинка3')),
                ('picture4', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/', verbose_name='Картинка4')),
                ('picture5', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d/', verbose_name='Картинка5')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category')),
            ],
        ),
    ]
